version: '3'

volumes:
  frontend:
  backend:
  database:
  nginx.conf:

services:
  frontend:
    image: nginx:latest
    ports:
      - 8087:80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./backend/:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
    links:
      - database
    container_name: nginx
  fpm:
    build:
      context: .
      dockerfile: ./backend/backend.dockerfile
    container_name: fpm
    ports:
      - 9000:9000
    volumes:
      - ./backend/:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - database
    links:
      - database
    env_file: ./backend/.env
  database:
    image: mysql:5.7.20
    container_name: database
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
